# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MarketDataFeed.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'MarketDataFeed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14MarketDataFeed.proto\x12%com.upstox.marketdatafeeder.rpc.proto\"\xc6\x01\n\x0eMarketDataFeed\x12O\n\x05\x66\x65\x65\x64s\x18\x01 \x03(\x0b\x32@.com.upstox.marketdatafeeder.rpc.proto.MarketDataFeed.FeedsEntry\x1a\x63\n\nFeedsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x44\n\x05value\x18\x02 \x01(\x0b\x32\x35.com.upstox.marketdatafeeder.rpc.proto.MarketFullFeed:\x02\x38\x01\"\xb1\x01\n\x0eMarketFullFeed\x12J\n\nindex_feed\x18\x01 \x01(\x0b\x32\x34.com.upstox.marketdatafeeder.rpc.proto.IndexFullFeedH\x00\x12\x46\n\x08ltp_feed\x18\x02 \x01(\x0b\x32\x32.com.upstox.marketdatafeeder.rpc.proto.LTPFullFeedH\x00\x42\x0b\n\tfull_feed\"D\n\rIndexFullFeed\x12\x19\n\x11last_traded_price\x18\x01 \x01(\x01\x12\x18\n\x10last_traded_time\x18\x02 \x01(\x03\"B\n\x0bLTPFullFeed\x12\x19\n\x11last_traded_price\x18\x01 \x01(\x01\x12\x18\n\x10last_traded_time\x18\x02 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MarketDataFeed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKETDATAFEED_FEEDSENTRY']._loaded_options = None
  _globals['_MARKETDATAFEED_FEEDSENTRY']._serialized_options = b'8\001'
  _globals['_MARKETDATAFEED']._serialized_start=64
  _globals['_MARKETDATAFEED']._serialized_end=262
  _globals['_MARKETDATAFEED_FEEDSENTRY']._serialized_start=163
  _globals['_MARKETDATAFEED_FEEDSENTRY']._serialized_end=262
  _globals['_MARKETFULLFEED']._serialized_start=265
  _globals['_MARKETFULLFEED']._serialized_end=442
  _globals['_INDEXFULLFEED']._serialized_start=444
  _globals['_INDEXFULLFEED']._serialized_end=512
  _globals['_LTPFULLFEED']._serialized_start=514
  _globals['_LTPFULLFEED']._serialized_end=580
# @@protoc_insertion_point(module_scope)
